.\" cursesmenus
.TH "cursesmenus" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
cursesmenus \- manual page for cursesmenus 0.0.0
.SH "SYNOPSIS"
.B cursesmenus
.SH "DESCRIPTION"
A CLI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
cursesmenus
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
